### ISSUE TITLE
Source string differs from its presentation

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/hosted#10]
https://hosted.weblate.org/translate/your-local-weather/strings/nb_NO/?checksum=c8fa1237ef890b5c

I am seeing 
"schwere Regenschauer", but when clicking to edit the source string, it says
"light rainshower"

Edit: When clicking [nearby strings](https://hosted.weblate.org/translate/your-local-weather/strings/nb_NO/?type=nottranslated#nearby), they are presented in English, but once clicked, seen overwritten in Norwegian Bokmål.

This suggests the source history gets overwritten when editing translated languages, as that is what happened most recently.

**Comment by nijel** [comment]
This seems to be another incarnation of https://github.com/WeblateOrg/weblate/issues/2144, certainly worth investigating.

**Comment by comradekingu** [comment]
@nijel It says the Repo is [17 hours out of date](https://hosted.weblate.org/projects/your-local-weather/strings/#alerts), but a user merged something 3 hours ago
https://hosted.weblate.org/user/thuryn1/

**Comment by nijel** [comment]
That should be fixed by https://github.com/WeblateOrg/weblate/commit/a8c25808cb9725d7f624d2ade325f356d0610868.

**Comment by comradekingu** [comment]
There are new source strings added to "czech" here https://hosted.weblate.org/changes/?page=9&limit=20&project=your-local-weather&component=strings
And the "schwere Regenschauer" is nowhere to be seen in the project history.
