### ISSUE TITLE
Libre software repos missing license info

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/hosted#13]
These are not listed in https://hosted.weblate.org/accounts/profile/#licenses

https://hosted.weblate.org/projects/dawnlightsearch/translations/
https://github.com/chg-hou/DawnlightSearch/blob/c%2B%2B-version/LICENSE

https://hosted.weblate.org/projects/godot-engine/godot-docs/
https://github.com/godotengine/godot-docs-l10n/blob/master/LICENSE.txt
https://github.com/godotengine/godot-docs-l10n/issues/1#issuecomment-445354959

https://hosted.weblate.org/projects/kiss/strings
https://github.com/Neamar/KISS/blob/master/LICENSE

https://hosted.weblate.org/projects/ksnip/translations
https://github.com/DamirPorobic/ksnip/blob/master/LICENSE

https://hosted.weblate.org/projects/onvifviewer/translations
https://gitlab.com/caspermeijn/onvifviewer/blob/master/LICENSE

https://hosted.weblate.org/projects/openaca_10/translations
https://gitlab.com/jorgemustaine/openaca_10/blob/master/LICENSE

https://hosted.weblate.org/projects/safe-surfer/translations
https://gitlab.com/safesurfer/SafeSurfer-Desktop/blob/master/LICENSE

https://hosted.weblate.org/projects/subway-tooter/strings
https://github.com/tateisu/SubwayTooter/blob/master/LICENSE.txt

https://hosted.weblate.org/projects/turris/foris-pakon-plugin
https://gitlab.labs.nic.cz/turris/foris-pakon-plugin/blob/master/LICENSE

https://hosted.weblate.org/projects/turris/foris-storage-plugin
https://gitlab.labs.nic.cz/turris/foris-storage-plugin/blob/master/LICENSE

https://hosted.weblate.org/projects/turris/foris-data_collect-plugin
https://gitlab.labs.nic.cz/turris/foris-data_collect-plugin/blob/master/LICENSE

**Comment by nijel** [comment]
@Naruto0 can you please go through these and update missing license information?

**Comment by nijel** [comment]
There is now alert indicating this as well.

**Comment by Naruto0** [comment]
Hi @nijel. It is done.

Regards, F.
