### ISSUE TITLE
Translation subrepo with no stated license info

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/hosted#14]
Not listed in https://hosted.weblate.org/accounts/profile/#licenses
Translation hosted in a subrepo of its own, without any specific license info:

https://hosted.weblate.org/projects/f-droid/fdroiddata/
https://gitlab.com/fdroid/fdroiddata-localizations
https://gitlab.com/fdroid/fdroiddata-localizations/issues/1

**Comment by nijel** [comment]
@eighthave this is probably more for you ;-).

**Comment by eighthave** [comment]
here you go:
https://gitlab.com/fdroid/fdroiddata-localizations/commit/104c49caa3e7f4a5f2afc30644d4d7dd0101647c

**Comment by nijel** [comment]
I've updated the Weblate project as well.
