### ISSUE TITLE
Source string differs from its presentation 2

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/hosted#16]
https://hosted.weblate.org/translate/wallabag/user/nb_NO/?checksum=7c2f797fac38ac4e
Says:

> Since you enable two factor authentication on your wallabag account and you just logged in from a new device (computer, phone, etc.), we send you a code to validate your connection.

Clicking to edit, it then says:

> Since you require two factor authentication to log in on your wallabag account, and a new device just used it, we send you a code to validate its connection.

The change upstream is here https://github.com/wallabag/wallabag/pull/3420/files

Is the translation the dev branch and the edit function master?

Possibly related to #10

**Comment by nijel** [comment]
The content was last loaded before fix for https://github.com/WeblateOrg/weblate/issues/2144, so it's most likely caused by that. I've forced reloading now and it's now correct.
