### ISSUE TITLE
Uploading component translation file does nothing?

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/hosted#17]
I thought enabling translation memory for a project would import all available matches, but no such luck. Is it one of the jobs that runs * times a day? (If so that isn't very clear when doing it.)

https://hosted.weblate.org/projects/peertube/android/nb_NO/#upload
Uploaded my own translation memory here, no change.

The first box here works (?) https://hosted.weblate.org/memory/project/peertube/
Also, I don't know why there are two, what is the difference between them?

What happened was the [total number of translated strings](https://hosted.weblate.org/stats/) went up by an expected amount, 
100+ or so, but the untranslated strings in the component are still unpopulated.

https://hosted.weblate.org/translate/peertube/android/nb_NO/?type=nottranslated

**Comment by nijel** [comment]
There is no automatic translation right now, it just shows up in the machine translation tab. The automation will come probably in a way of suggestions, see https://github.com/WeblateOrg/weblate/issues/2541

**Comment by comradekingu** [comment]
Updated firstpost.
I would want to add 100% matches as translations marked as needing work. The #upload section permits this, but it doesn't take effect till the job runs? If it doensn't do anything, then is it broken, or should it not be offered to users? (I am not an admin on PeerTube).

Why there are two seemingly identical sections in /memory/project/peertube/ for uploading strings I don't know? Neither offers any option.

In https://hosted.weblate.org/translate/peertube/android/nb_NO/?checksum=c5755e5032d1414f it looks like strings are imported into machine translation by default (though I have never used this function). The only strings from "Weblate translation memory" are from projects where I know TM has been turned on by the admin.

There is also an entry for "Weblate Translation Memory (Prosjekt: weblate-memory.json)", what is that?
