### ISSUE TITLE
Down for maintenance not translatable.

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/hosted#2]
Ran into this breifly.
![skjermbilde pa 2018-10-21 17-37-04](https://user-images.githubusercontent.com/13802408/47268999-20448580-d558-11e8-82f7-391b8317bcf4.png)
"Hosted Weblate is down for maintenance!"

**Comment by nijel** [comment]
This happens when updating the server, what I did today...

**Comment by comradekingu** [comment]
@nijel Yes, I would expect to see it localized for a more welcoming experience.

**Comment by nijel** [comment]
This is just a static page when Weblate is not running at all, no localization is possible there. Also it would have no access to session data to know user language...
