### ISSUE TITLE
Can't open any projects

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/hosted#22]
Trying to open
https://hosted.weblate.org/projects/userli/messages/nb_NO/
throws internal server error
7d1da5e4bebb4fe796cb79a009e2567f

![image](https://user-images.githubusercontent.com/13802408/59499431-ae7acc80-8e97-11e9-9455-6bfce3608641.png)

**Comment by nijel** [comment]
Fixed, thanks for reporting.
