### ISSUE TITLE
Projects for removal

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/hosted#227]
https://hosted.weblate.org/projects/obama/#information

There are others, will keep pasting them here.

**Comment by comradekingu** [comment]
I have my doubts about https://hosted.weblate.org/projects/abodva-appstore/#information
Maybe de-list it for the time being? (Idea being to limit exposure for similar efforts)

**Comment by comradekingu** [comment]
@nijel Chances of https://hosted.weblate.org/projects/veas/#information being a genuine effort are slim.

**Comment by orangesunny** [comment]
> [InsightIM/Tok-Android#7](https://github.com/InsightIM/Tok-Android/issues/7) over at https://hosted.weblate.org/projects/tok/ A swift request for comment and shortly removal is in order.

Thanks, deleted!

**Comment by comradekingu** [comment]
https://hosted.weblate.org/projects/ahmedios7/#information is highly suspect.
Either it is a misguided way of doing things, or an advert for a different translation service.

Suggest removing the URL.

**Comment by orangesunny** [comment]
> https://hosted.weblate.org/projects/ahmedios7/#information is highly suspect. Either it is a misguided way of doing things, or an advert for a different translation service.
> 
> Suggest removing the URL.

removed, thanks for the tip

**Comment by comradekingu** [comment]
https://hosted.weblate.org/projects/how-to-borrow-money-from-cash-app/#information strikes me as particularly suspicious.

**Comment by orangesunny** [comment]
> https://hosted.weblate.org/projects/how-to-borrow-money-from-cash-app/#information strikes me as particularly suspicious.

thanks @comradekingu! Removed.

**Comment by comradekingu** [comment]
Back today with https://hosted.weblate.org/projects/cash-app/#information
Banning the account might be a deterrence? Not sure if that was already done.

**Comment by comradekingu** [comment]
https://hosted.weblate.org/projects/voiture/#information
and
https://hosted.weblate.org/projects/katsula-pharma-monographs

**Comment by comradekingu** [comment]
https://hosted.weblate.org/projects/jerettjeff/#information

**Comment by orangesunny** [comment]
> https://hosted.weblate.org/projects/jerettjeff/#information 
Thank you, removed.

> Also, https://hosted.weblate.org/contributor-agreement/aurowallet/auro-wallet-browser-extension/ should not fly.
Yes, that one is suspicious. Will exchange some e-mails with the author. Not suitable for libre hosting with that CA.

**Comment by comradekingu** [comment]
https://hosted.weblate.org/projects/att-password-reset/#information

**Comment by orangesunny** [comment]
> https://hosted.weblate.org/projects/att-password-reset/#information

Thank you, @comradekingu. This scam is deleted.

**Comment by comradekingu** [comment]
https://hosted.weblate.org/projects/889nation-situs-slot-pulsa-tanpa-potongan-terpercaya/#information

**Comment by nijel** [comment]
https://hosted.weblate.org/projects/fabric-modmenu/

**Comment by orangesunny** [comment]
> https://hosted.weblate.org/projects/fabric-modmenu/

Thanks! I removed the announcement, notified the maintainers so they can download current work if they wish, and scheduled it for removal.

**Comment by comradekingu** [comment]
https://hosted.weblate.org/projects/delhi-escorts-pritychavda-in/#information is some escort service.

**Comment by comradekingu** [comment]
https://hosted.weblate.org/projects/cytotec-available-in-uae-971525196596-oman-bahrain-saud/#information is unquestionably shady

**Comment by orangesunny** [comment]
Thanks, removed.

**Comment by comradekingu** [comment]
https://l10n.elementary.io/translate/mail/mail/nb/?q=state:%3Ctranslated
links to Poeditor, which doesn't help anyone looking to use superior tooling.

**Comment by orangesunny** [comment]
> https://l10n.elementary.io/translate/mail/mail/nb/?q=state:%3Ctranslated links to Poeditor, which doesn't help anyone looking to use superior tooling.

I don’t see the links. And if I would, I can’t do anything with it. Elementary host their Weblate independently.

**Comment by comradekingu** [comment]
@orangesunny My bad, got the wrong URL.
https://hosted.weblate.org/projects/erp/#information is the one to remove.

**Comment by orangesunny** [comment]
done

**Comment by comradekingu** [comment]
https://hosted.weblate.org/projects/test-ama/#information
My guess is someone isn't trying to get that adult website translated.

**Comment by orangesunny** [comment]
Yes, no place for that on Hosted.

**Comment by comradekingu** [comment]
So this https://github.com/frenck/spook/issues/314
doesn't actually run afoul of
https://hosted.weblate.org/hosting/

(because the source code is in the open, and the translation content is freely licensed)

which is why I don't understand putting effort into specifically allowing it…

"Source code that is open"-software shouldn't be in the "Libre" plan at all,
as that just undermines the whole concept.

Yes, the hosting itself is Libre, but that seems like a further attempt at fooling people into contributing in good faith.

**Comment by comradekingu** [comment]
https://hosted.weblate.org/projects/brooklin-dental-centre-your-best-whitby-dental-office-for-e/#information seems like straight advertisement.

**Comment by comradekingu** [comment]
@orangesunny https://hosted.weblate.org/projects/cenforce-100-tablet-treated-impotence-issues-powpills/#information is a clear violation.

**Comment by orangesunny** [comment]
Thank you! Removed.

**Comment by comradekingu** [comment]
@orangesunny 
https://hosted.weblate.org/projects/fildena-100-mg-an-effective-medication-for-erectile-dysfunc/#information

**Comment by nijel** [comment]
I've just removed that one.

**Comment by comradekingu** [comment]
_Thankfully_ https://github.com/DBSG-Captain doesn't have any source code, so
https://hosted.weblate.org/projects/lockdown-dom/ can be removed.

**Comment by comradekingu** [comment]
https://hosted.weblate.org/projects/custom-crosshair-mod/en_gb/#information
is NC-licensed
https://github.com/wjbaker101/ccm-mc_latest-fabric/blob/master/LICENSE

**Comment by orangesunny** [comment]
> https://hosted.weblate.org/projects/custom-crosshair-mod/en_gb/#information is NC-licensed https://github.com/wjbaker101/ccm-mc_latest-fabric/blob/master/LICENSE

Investigating, thanks.

**Comment by comradekingu** [comment]
https://hosted.weblate.org/projects/uje/website-copy-uje-oil-bar/#information is the website of a restaurant,
which loads a bunch of https://sentry.dotyourspot.com cancer, so maybe tell them in a nice way to
share the code or pay for the service?

**Comment by orangesunny** [comment]
> https://hosted.weblate.org/projects/miniskins/miniskins/#information has no license, nor code/license in https://github.com/graytoowolf/Translations

they are still setting up. There is some code at https://github.com/graytoowolf/MiniSkins which is the same GitHub Org, so could be OK. Let’s give them time for the setup before they ask for approval

**Comment by orangesunny** [comment]
> https://hosted.weblate.org/projects/uje/website-copy-uje-oil-bar/#information is the website of a restaurant, which loads a bunch of https://sentry.dotyourspot.com cancer, so maybe tell them in a nice way to share the code or pay for the service?

Thanks, switched to commercial trial and communicating.

**Comment by comradekingu** [comment]
https://hosted.weblate.org/projects/pay-for-my-assignment/#information
should be de-listed.
The info field is used for an advert.

**Comment by orangesunny** [comment]
Removed. Thank you!
