### ISSUE TITLE
Use the Website subscription page instead of the Hosted one

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/hosted#25]
https://hosted.weblate.org/create/billing/?upgrade=1 does not instil a lot of confidence.
The numbers also look strange.
![bilde](https://user-images.githubusercontent.com/13802408/62402403-e93fdd80-b587-11e9-9382-485ccf6918da.png)

https://weblate.org/hosting/ looks and functions a lot better, why not go straight there?

Is it specific to Hosted, or a way to handle subscriptions on the platform without running a website?

https://hosted.weblate.org/create/project/ also links to the older style site.

**Comment by nijel** [comment]
The pricing mess was caused by wrong translation, it included the additional "1".

The long term plan is to move all billing to weblate.org, but it needs some development effort to be able to do that.
