### ISSUE TITLE
Non-free project on Hosted

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/hosted#27]
The content on https://hosted.weblate.org/projects/publishing-is-coding-change-my-mind/_links/nb_NO/ is not under a libre license https://perrotuerto.blog/content/html/en/_fork.html

It is actually actively not a libre license, because it restricts use. The code for the project of hosting it is, but this effort of translating it concerns the content, at-least in part. The translation effort is licensed under its custom license.

Upstream didn't answer, and the project overall pollutes the translation memory with bad language.

https://hosted.weblate.org/projects/publishing-is-coding-change-my-mind/001_free-publishing/#information It represents itself as "Libre" on its website, and "Free and open" on Hosted "Open and Free Publishing License (LEAL)" https://hosted.weblate.org/projects/publishing-is-coding-change-my-mind/001_free-publishing/#information

This undermines not only the general effort of Hosted, but the very nature of what that effort is.

**Comment by nijel** [comment]
@orangesunny can you please check this?

**Comment by orangesunny** [comment]
Hi, @comradekingu, thank you very much for heads up. I deleted the project, and I will communicate it with the upstream.
