### ISSUE TITLE
Illegal/misleading/missing license info for armellolocalization/hiri

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/hosted#30]
https://hosted.weblate.org/projects/armellolocalization/armello-public/#information
says "Please see the Contribution License Agreement", which is not a license.
It should say "non-free(?), unpaid commission"

It links to https://bitbucket.org/leagueofgeeks/armelloprivatelocalization.git for source code, I would have a look, but I need to reset my two-factor to do so.

The other non-free project on public Hosted
https://hosted.weblate.org/projects/hiri/translations/#information
says "Proprietary" (which a license can be in the sense of custom, and still be free)

WeblateOrg/weblate#2141 is still an issue

There is a source code link to https://github.com/kevdkav/hiri-translate.git which contains zero source code:
From the license:

 There is a link which (still) says:

> Intellectual Property
> 
> The Service and its original content, features and functionality are and will remain the exclusive property of Whittl Media Ltd and its licensors. The Service is protected by copyright, trademark, and other laws of both the Ireland and foreign countries. Our trademarks and trade  dress may not be used in connection with any product or service without the prior written consent of Whittl Media Ltd.

Translations are not original content of the service, and no jurisdiction worth anything would accept signing away unpaid and contractless work as "features". This means "Whittl Media Ltd and its licensors" can't use it, and should (rightly) pay translators to do so.

I think having non-free potentially malicious services with such huge surfaces that operate this way harms the otherwise excellent reputation of Hosted Weblate.

**Comment by nijel** [comment]
The projects with OSI/FSF licenses are highlighted on Hosted Weblate. In case the project doesn't have this, it's translator choice whether he wants to contribute to such project or not. There are certainly translators who would never contribute to such projects and there are ones which are happy to contribute. I'm not the one to decide where people should be contributing or not.

Hosted Weblate is service for both libre and commercial translations. The commercial ones actually make it possible to provide service for free to the libre ones.

**Comment by nijel** [comment]
PS: Partly it's related to https://github.com/WeblateOrg/weblate/issues/2769 that we don't have structured information on the licenses. Once we have that, the license description for such projects would be consolidated as well.
