### ISSUE TITLE
Addition of admins

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/hosted#34]
I think the admin stuff was in the addons, which is now gone.
Would be nice to have still. The ideal being to add admins that can do all the notifications and adding screenshots, without touching anything dangerous.

A nice idea would be to do it from a file in the project (Git) repo. That way it is not something regular maintainers need to interface with Weblate UI to do.

**Comment by nijel** [comment]
You mean user management? See https://docs.weblate.org/en/latest/admin/access.html

**Comment by comradekingu** [comment]
I confused myself by trying to find it on a project I didn't already administrate.
Project settings and whatnot could be available to all but grayed out for non-admins.
Closing. My bad, sorry.
