### ISSUE TITLE
Users for removal

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/hosted#344]
### Describe the issue

https://hosted.weblate.org/changes/?page=834&limit=20&user=realOwlgram banned and strings reverted

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

https://hosted.weblate.org/search/nekox/?offset=1&q=Owlgram+is+better&sort_by=-priority%2Cposition&checksum=

### Additional context

First and last page of history for "realOwlgram" is all that string.

**Comment by orangesunny** [comment]
This user, and some others damaging the same project, are already blocked from using Hosted Weblate since the start of this week. They can't log in or change anything, no need to delete them.
