### ISSUE TITLE
"Maintenance in progress" untranslated

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/hosted#35]
Is this part of Weblate?

"Maintenance in progress
We're sorry, but this site is currently down for maintenance."

![bilde](https://user-images.githubusercontent.com/13802408/72763049-3705dc00-3be2-11ea-96ef-9d6d0d2bad38.png)

Also says "Service status" at the bottom.

**Comment by nijel** [comment]
It can not be translated as it is just a static page served when backend is down.

**Comment by nijel** [comment]
Now they are translatable on https://hosted.weblate.org/projects/weblate/hosted-error-pages/ using https://docs.weblate.org/en/latest/admin/addons.html#javascript-localization-cdn (see https://github.com/WeblateOrg/weblate/issues/4024).
