### ISSUE TITLE
Closed source project using AGPLv3 translation license

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/hosted#36]
There is no way to tell gapp selfservice is closed source
https://github.com/ticgal/gapp/issues/12#issuecomment-577237080

![bilde](https://user-images.githubusercontent.com/13802408/72943554-9e549500-3d76-11ea-8bc1-d5aab52650a8.png)
https://hosted.weblate.org/projects/gapp/#information

---

![bilde](https://user-images.githubusercontent.com/13802408/72943588-b88e7300-3d76-11ea-8dcd-2715d9ffe5c1.png)

There is also no quick way to delete all user contributions to a single project.

**Comment by comradekingu** [comment]
@orangesunny

Could this project be removed? They have no regard for law, and no intention of being able to use the translations made on Hosted Weblate. It is just a waste of effort, even to the tune of having ones translation deleted…

https://github.com/ticgal/gapp/issues/12

**Comment by orangesunny** [comment]
It was not the right thing to do, but mistakes happen and they said sorry. The only way to correct what happened was to remove the translations and they did it. They also changed the license, no longer using AGPLv3. I cannot remove their project, they are paying for the hosting. I see they have it CCA4.0 now, which should be OK if they mention the authors of the translation in their apps. Or am I wrong?

**Comment by comradekingu** [comment]
Only my translation was deleted, not by mistake.
Some of the translations are older than the license change
https://hosted.weblate.org/changes/?page=53&limit=20&component=gapp-selfservice&project=gapp
and for example https://hosted.weblate.org/projects/gapp/gapp-selfservice/ru/#activity
The sensible way to do it is to ask all translators to re-license their translations.
The admin can of course delete translations if that is seen as a better option.
It is however not up to the project admin to change the license from the freedoms granted by AGPLv3+ to Creative Commons Attribution 4.0 International. This is not just my position.

Crediting translators is just an additional problem added to the present and newly created issues to solve.

Though it didn't happen to my strings here, if this is a case of loopholing translations through the translation memory for sale to projects like this I find it unacceptable to me in adding anything else to it.
