### ISSUE TITLE
Licensing info does not pick up GPL any later version

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/hosted#37]
I checked the 5 first projects in the [license list](https://hosted.weblate.org/accounts/profile/#licenses) with GPL*-only, and they are all "or any later version", GPLv*+

https://github.com/airsonic/airsonic/blob/master/LICENSE.txt
https://gitlab.com/librebob/athenaeum/blob/master/LICENSE
https://gitlab.com/ar-/apple-flinger/blob/master/COPYING
https://github.com/drpout/boilr/blob/master/LICENSE

What gives? I did put in links to the actual license file for a lot of projects, but it seems those have gone.

**Comment by nijel** [comment]
The license link was removed in #2769. The license was however migrated as it was specified, none of these specified or later. As written in the issue, we really didn't have this well covered before...

Linking to COPYING/LICENSE file is pretty much useless, as it is anyway supposed to contain original license text, no matter whether project is GPL3 only or also allows later version:

> Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.
