### ISSUE TITLE
Translation licenses erroneously not "or later"

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/hosted#39]
Many licenses are listed as "GPLv*-only", when the upstream source repo is "or later".
I can't remember exactly when this happened, but fixing it as soon as possible is preferable.
If given the access I am willing to go through every single project to make sure the licensing info is correct, change it around, and notify upstream that this has happened.

**Comment by nijel** [comment]
Ah, this was already reported in https://github.com/WeblateOrg/hosted/issues/37, but I focused only on the link part there, sorry.

**Comment by comradekingu** [comment]
Ah, my bad, didn't think to look there.

**Comment by orangesunny** [comment]
still on it

**Comment by comradekingu** [comment]
List of AGPLv3 only with AGPLv3+ in project license
https://hosted.weblate.org/projects/koreader/koreader/#information
https://github.com/koreader/koreader/blob/master/COPYING

**Comment by nijel** [comment]
> List of AGPLv3 only with AGPLv3+ in project license (Should be changed to or-later in WL)

I've just changed all these, thanks for going through the list.

> https://hosted.weblate.org/projects/noosfero/#information 

This project is several months behind upstream and has merge errors, I've asked them whether it is still used.

> https://hosted.weblate.org/projects/rero_plus/rero-ils/#information

Seems fixed now.

> https://hosted.weblate.org/projects/jasp/

Seems all to be or later, adjusted accordingly.

**Comment by nijel** [comment]
I've clicked for most of the projects and seems to be fixed now.
