### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/hosted#40]
http://www.seowebpageanalyzer.com has some low-hanging problems
https://suite.seotesteronline.com/seo-checker/aHR0cDovL2hvc3RlZC53ZWJsYXRlLm9yZw==/content

Better summary

IP Canonicalization / htaccess 301 redirect

Suggested keywords:
"web translation platform"
web based translation platform"
"website localization platform"
"website translation platform"
"migrate instead of syncdb"
"component documentation"
"web translation platform"
"web based translation"
"web based translation platform"
"cloud based localization tool"

There is no rel next meta tag on this page.
There is no rel prev meta tag on this page.

Missing alt tag on this
https://s.weblate.org/hosted/static/logo-128.png

For weblate.org

https://www.woorank.com/en/www/hosted.weblate.org
says the tap targets on mobile aren't big enough

Get .biz .net .info .com etc now that .org is going to suck.

The amount of tags is very high (15). We recommend using a maximum of 10 tags for this page.

**Comment by nijel** [comment]
I think that "analyzer" is quite outdated, so I'm not sure that it points make sense.

* Keywords are not really used by search engines these days (see for example https://support.seomanager.com/article/30-keywords-meta-field-is-no-longer-used-by-google).
* www redirection, really?
* social interaction seems just broken.

**Comment by comradekingu** [comment]
Social interaction is a bunch of cancer. I think scoring lower there is better.
