### ISSUE TITLE
Explore the possibility of making Weblate SAML identity provider

### ISSUE THREAD

**Issue by orangesunny** [WeblateOrg/hosted#42]
It would be super useful for the new support system, for other systems in the future, maybe too.

There is https://pypi.org/project/django-python3-saml/ that might help.

**Comment by nijel** [comment]
This one is dead (last commit two years ago), that's why I've mentioned https://pypi.org/project/djangosaml2idp/

**Comment by orangesunny** [comment]
👍
Sorry, I didn’t click on all the links. 😬

**Comment by nijel** [comment]
Deployed, but doesn't seem to work with Zammad, works with test SAML service providers, so it's most likely a configuration issue.
