### ISSUE TITLE
Unclear new terms

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/hosted#502]
(I remember writing this once before, so If I got that posted somewhere I am sorry about the duplication here.)
### Describe the issue

https://hosted.weblate.org/legal/confirm/?next=%2F
says
Within the meaning of [Article 7](http://www.privacy-regulation.eu/en/7.htm) of the GDPR the User hereby gives consent to collecting, storage, and processing of the Personal Data according to the [Privacy Policy](https://hosted.weblate.org/legal/privacy/).

>Payment processors when purchasing a service from us.

For case of argument, this could be Weblate selling said data?

Did anything else change, and does the above represent anything actually changing?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Open Hosted.weblate.org
2. Get new terms to sign

**Comment by nijel** [comment]
No, this means that payment processor will get some of your data when you purchase a service.

**Comment by orangesunny** [comment]
@comradekingu 

As @nijel says, this is to clarify the event when you purchase a service from Weblate. As we are not a financial institution, we work with our banks (and card-payment gateway provider if you pay by card) to process the purchase. The only customer data passed from us to the payment provider is currently e-mail in case of card payment.

Weblate never sold, does not, and will never sell any data.

We discussed the new version of the terms with privacy-focused people from FOSS communities like MetaBrainz and EFF. The scope was to make it more specific and less broad. To cut out unessential parts and provide better-descriptive Overview points. Changes’ description is on https://github.com/WeblateOrg/wllegal/pull/551.

But nothing is perfect, thanks for your feedback.

Would this line be better in your understanding?
_If you purchase a service from us, payment processors get access to your data limited to the bare minimum needed to process your payment. This is usually an e-mail address._

**Comment by comradekingu** [comment]
Yes, but "data" → "Personal Data", insofar as an e-mail can qualify as such under EU-GDPR.
https://www.cognitivelaw.co.uk/gdpr-issues-do-work-emails-count-as-personal-data/

Something like:
If you additionally choose to purchase a service from us, the respective payment processor gets required access to your Personal Data, limited to the bare minimum needed to process the payment. This usually means an e-mail address.

And time of purchase?

**Comment by orangesunny** [comment]
> Yes, but "data" → "Personal Data", insofar as an e-mail can qualify as such under EU-GDPR. https://www.cognitivelaw.co.uk/gdpr-issues-do-work-emails-count-as-personal-data/
> 
> Sometimes it is "personal data" https://github.com/WeblateOrg/wllegal/pull/551/files#diff-8668d587fc1d9720568f6de141756d74b8efd482a5e3d877db8fb3fd8996b0fbR4
> 
> https://github.com/WeblateOrg/wllegal/pull/551/files#diff-78697848a893885789cd5ef7e6ac9082bfd4cd43084075a4535e7893e2721064R20

Overview does not explain what personal data is, is not legally binding, neither it is a legal document. It’s only a TL;DR for easier orientation. Thus, no term (capital letters) is used. In documents, it is consistently used as a term. If not, I don’t see it and it should be corrected.



> In any event, something like:
> If you additionally choose to purchase a service from us, the respective payment processor gets required access to your Personal Data, limited to the bare minimum needed to process the payment. This usually means an e-mail address.

Here is what seems best from your and my look combined: https://github.com/WeblateOrg/wllegal/pull/575/files

> Time of purchase, and the amount?

- We do not share TOP with payment processor, that’s generated automatically on their side. Weblate only cares about success of the payment.
- We do share the amount, but I don’t see it as PD. Should I? 🤔 
- Never mind, these are only examples, we do not want to spell out what PD we share with the processor in PP as that can change if we switch the processor. Such a change would then mean a new agreement from every user (even not affected) with ToS & PP every time, which would generate too many unessential changes.
