### ISSUE TITLE
Service down

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/hosted#562]
### Describe the issue

Can't reach Hosted Weblate today.
Don't know if that is planned or not.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to https://hosted.weblate.org/
2. 404

### Screenshots

![image](https://github.com/WeblateOrg/hosted/assets/13802408/365f330b-16da-4f99-84eb-359bcf93617a)

**Comment by comradekingu** [comment]
Works now. :)

**Comment by nijel** [comment]
There is https://status.weblate.org/ which tells you there is a scheduled maintenance going on today... See also https://github.com/weblate-status-bot/status/issues/570
