### ISSUE TITLE
weblate account gitlab API token is expired

### ISSUE THREAD

**Issue by berrange** [WeblateOrg/hosted#706]
### Describe the issue

I received an email alert on my libosinfo/osinfo-db project saying the following

> ## Could not push the repository.
> 
> Weblate could not push changes to the upstream repository.
> 
>  Could not get project: invalid_token, Token is expired. You can either do re-authorization or token refresh.

I believe this means that its GitLab API token has expired

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

This was an automated email sent by weblate, presumably when it tried to push new translated strings to our gitlab repository.

### Expected behavior

Weblate can push to gitlab repositories

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
Fixed.

**Comment by hydrandt** [comment]
@nijel We get the same alert today for https://hosted.weblate.org/projects/ark/ark-web-frontend/, I thought that I have to refresh a token, but it seems that this is a token for the whole instance?

**Comment by nijel** [comment]
The token should be updated now.

**Comment by linsui** [comment]
I still get this alert

> Could not push F-Droid/F-Droid: Could not get GitLab project (401): invalid_token, Token is expired. You can either do re-authorization or token refresh.

**Comment by nijel** [comment]
🤦 I set the token expiry for today. It should be fixed now for real.

**Comment by linsui** [comment]
Lol, thanks!

**Comment by raggesilver** [comment]
I think this just happened again. Sorry for the ping 😬

**Comment by nijel** [comment]
@raggesilver Maybe different issue? This token is definitely not expired.

**Comment by raggesilver** [comment]
> [@raggesilver](https://github.com/raggesilver) Maybe different issue? This token is definitely not expired.

I am sure I might be doing something wrong, but the error does look the same.

<img width="1458" height="326" alt="Image" src="https://github.com/user-attachments/assets/ca746f82-a449-40f6-a856-b56c697ec9bc" />

https://hosted.weblate.org/projects/blackbox/

**Comment by nijel** [comment]
Ah, that's for gitlab.gnome.org, fixing that now.
