### ISSUE TITLE
Linda_test missing license information

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/hosted#9]
https://hosted.weblate.org/projects/linda_test/#information

The name should be "Tunstall" too.
I unequivocally retain sole copyright as the creator of current translations, as per Norwegian copyright law. I did this to test whether it is deleted or if I am asked to relicense.

The responsibility to maintain updated copyright licenses falls on the DPO, as per GDPR info available on the platform.

**Comment by nijel** [comment]
This test project was mistakenly public, I've just fixed that.
